@startuml
interface IMethod{
    method1():void
    method2():void
    method3():void
    method4():void
    method5():void
}
class MethodImpl
IMethod <|.. MethodImpl
class Client
Client ..> MethodImpl

@enduml